name: task_manager_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  # Parse SDK for Flutter to integrate with Back4App
  parse_server_sdk_flutter: ^7.0.1
  flutter:
    sdk: flutter
  url_launcher: ^6.1.8

  # UI-related dependencies
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.7
  table_calendar: ^3.0.9
  flutter_localizations:
    sdk: flutter
  intl: any

  # State management and shared preferences
  flutter_bloc: ^8.1.2
  bloc_concurrency: ^0.2.0
  shared_preferences: ^2.2.2

# dependency_overrides:
#   sembast: ^3.8.0
#   idb_shim: ^2.3.2
#   sembast_web: ^2.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  # Mocking for unit tests
  mocktail: ^1.0.4

  # Linter for Flutter/Dart code
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/
    - assets/images/home_page_image.png
    - assets/images/signup_now.png
    - assets/images/add_user.png

  fonts:
    - family: Sora
      fonts:
        - asset: assets/fonts/Sora-Light.ttf
        - asset: assets/fonts/Sora-Regular.ttf
